spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'FALSE'
        enable_lazy_load_no_trans: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
    defer-datasource-initialization: true
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/docnote?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
logging:
  level:
    org:
      springframework:
        security: INFO
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  error:
    include-binding-errors: always
    include-message: always
  port: 8080
